services:
  # MongoDB
  cadmus-codicology-mongo:
    image: mongo
    container_name: cadmus-codicology-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --logpath=/dev/null # --quiet
    ports:
      - 27017:27017
    networks:
      - cadmus-codicology-network

  # PostgreSQL
  cadmus-codicology-pgsql:
    image: postgres
    container_name: cadmus-codicology-pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - cadmus-codicology-network
    # volumes:
      # ensure you have created the var/db/pgsql folder in the host
      # https://hub.docker.com/r/postgis/postgis
      # - /var/db/pgsql:/var/lib/postgresql/data

  cadmus-codicology-api:
    image: vedph2020/cadmus-codicology-api:8.0.7
    container_name: cadmus-codicology-api
    ports:
      # https://stackoverflow.com/questions/48669548/why-does-aspnet-core-start-on-port-80-from-within-docker
      - 5152:8080
    depends_on:
      - cadmus-codicology-mongo
      - cadmus-codicology-pgsql
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-codicology-mongo:27017/{0}
      - CONNECTIONSTRINGS__AUTH=Server=cadmus-codicology-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - CONNECTIONSTRINGS__INDEX=Server=cadmus-codicology-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - SEED__DELAY=20
      - MESSAGING__APIROOTURL=http://cadmusapi.azurewebsites.net
      - MESSAGING__APPROOTURL=http://cadmusapi.com/
      - MESSAGING__SUPPORTEMAIL=support@cadmus.com
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-codicology-mongo:27017/cadmus-logs
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
    networks:
      - cadmus-codicology-network

  cadmus-codicology-app:
    image: vedph2020/cadmus-codicology-shell:13.0.11
    container_name: cadmus-codicology-app
    ports:
      - 4200:80
    depends_on:
      - cadmus-codicology-api
    networks:
      - cadmus-codicology-network

networks:
  cadmus-codicology-network:
    driver: bridge
