allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@myrmidon/cadmus-part-general-pg@18.0.0 || 20.0.0'
  - '@myrmidon/cadmus-part-general-ui@18.0.1 || 18.0.3 || 18.0.4 || 20.0.0'
  - '@myrmidon/cadmus-part-philology-pg@18.0.0 || 20.0.0'
  - '@myrmidon/cadmus-part-philology-ui@19.0.1 || 19.0.3 || 20.0.0'
  - '@myrmidon/cadmus-text-ed-md@12.0.0'
  - '@myrmidon/cadmus-text-ed-txt@11.0.0'
  - '@myrmidon/cadmus-text-ed@11.0.0'
  - '@myrmidon/cadmus-ui-note-set@12.0.0'
  - '@testing-library/jest-dom@7.0.0'
  - marked@18.0.7 || 18.0.14
  - '@myrmidon/cadmus-cod-location@10.0.3'
  - '@myrmidon/cadmus-refs-lookup@11.0.5 || 11.0.6'
  - '@analogjs/vite-plugin-angular@2.7.5'
  - '@rollup/rollup-win32-arm64-msvc@4.63.5'
  - '@myrmidon/cod-layout-view@2.0.3'
  - '@vitest/mocker@5.0.2'
  - '@vitest/spy@5.0.2'
  - vitest@5.0.2
  - '@myrmidon/cadmus-item-editor@18.0.1 || 20.0.0'
  - '@myrmidon/cadmus-ui@18.0.1 || 20.0.0'
  - '@angular-devkit/architect@0.2202.1'
  - '@angular-devkit/core@22.2.1'
  - '@angular-devkit/schematics@22.2.1'
  - '@angular/build@22.2.1'
  - '@angular/cli@22.2.1'
  - '@myrmidon/cadmus-api@20.0.0'
  - '@myrmidon/cadmus-core@20.0.0'
  - '@myrmidon/cadmus-flags-pg@20.0.0'
  - '@myrmidon/cadmus-flags-ui@20.0.0'
  - '@myrmidon/cadmus-graph-pg-ex@20.0.0'
  - '@myrmidon/cadmus-graph-pg@20.0.0'
  - '@myrmidon/cadmus-graph-ui-ex@20.0.0'
  - '@myrmidon/cadmus-graph-ui@20.0.0'
  - '@myrmidon/cadmus-item-list@20.0.0'
  - '@myrmidon/cadmus-item-search@20.0.0'
  - '@myrmidon/cadmus-preview-pg@20.0.0'
  - '@myrmidon/cadmus-preview-ui@20.0.0'
  - '@myrmidon/cadmus-profile-core@20.0.0'
  - '@myrmidon/cadmus-state@20.0.0'
  - '@myrmidon/cadmus-thesaurus-editor@20.0.0'
  - '@myrmidon/cadmus-thesaurus-list@20.0.0'
  - '@myrmidon/cadmus-thesaurus-ui@20.0.0'
  - '@schematics/angular@22.2.1'
  - ng-packagr@22.2.4
